version: 1.0.{build}
branches:
  only:
  - /master/
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  project: 7zFontChange.sln
  verbosity: minimal
artifacts:
- path: $(Configuration)
  name: 7zFontChange$(APPVEYOR_BUILD_VERSION)
